#!/usr/bin/env php
<?php
/**
 * Created by PhpStorm.
 * User: rtwf6589
 * Date: 06/08/14
 * Time: 11:37
 */

// app/console

use Rebangm\Checker;
use Rebangm\Checker\Application;


// installed via composer?
if (file_exists($a = __DIR__.'/../../autoload.php')) {
    require_once $a;
} else {

    require_once __DIR__.'/vendor/autoload.php';
}

$application = new Application();
$application->run();